### ISSUE TITLE
Manage cluster for scaling

### ISSUE THREAD

**Issue by claustres** [kalisio/kaabah#1]
Instead of generating instances for each domain generate a Swarm master + a set of Swarm workers.
- [x] Swarm infrastructure
- [x] Traefik 
- [x] Portainer
- [x] Prometheus
- [x] S3 backend to store the states 
- [x] Support https/Let's encrypt
- [x] Operational workflow 

Interesting example: https://github.com/stefanprodan/scaleway-swarm-terraform.

**Comment by cnouguier** [comment]
Another reference: https://github.com/GoContainer/swarm-terraform-scaleway

**Comment by cnouguier** [comment]
http://clescot.com/2017/04/29/2017-04-28-interet-deploiement-cluster-swarm-mode-terraform/

**Comment by cnouguier** [comment]
- [ ] Swarm infrastructure
- [ ] Traefik 
- [ ] Portainer
- [ ] Prometheus
- [ ] S3 backend to store the states 
- [ ] Operational workflow

**Comment by cnouguier** [comment]
Warning when seeting up the S3 backend: https://github.com/hashicorp/terraform/issues/12768

**Comment by cnouguier** [comment]
S3 backend also supports state locking and consistency checking via Dynamo DB, which can be enabled by setting the dynamodb_table field to an existing DynamoDB table name => do we go for state locking ?

**Comment by cnouguier** [comment]
We managed to deploy an application (Akt'n'Map) on the cluster. It sounds good.

The aktnmap.yml:
```
version: '3'

services:
  app:
    image: kalisio/${APP}:${VERSION_TAG}
    depends_on:
      - mongodb
    ports:
      - ${PORT}:8081
    environment:
      - GOOGLE_MAIL_USER=${GOOGLE_MAIL_USER}
      - GOOGLE_MAIL_PASSWORD=${GOOGLE_MAIL_PASSWORD}
      - GOOGLE_USER=${GOOGLE_USER}
      - GOOGLE_PASSWORD=${GOOGLE_PASSWORD}
      - GITHUB_USER=${GITHUB_USER}
      - GITHUB_PASSWORD=${GITHUB_PASSWORD}
      - APP_SECRET=${APP_SECRET}
      - SNS_ACCESS_KEY=${SNS_ACCESS_KEY}
      - SNS_SECRET_ACCESS_KEY=${SNS_SECRET_ACCESS_KEY}
      - SNS_ANDROID_ARN=${SNS_ANDROID_ARN}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - BUILD_NUMBER=${BUILD_NUMBER}
      - NODE_APP_INSTANCE=${FLAVOR}
      - DB_URL=mongodb://mongodb:27017/${APP}
    networks:
      - app-network

  mongodb:
    image: mongo
    volumes:
      - mongodb_app:/data/db
    networks:
      - app-network

volumes:
  mongodb_app:

networks:
  app-network:
    external:
      name: ${NETWORK}
```
The aktnmap.swarm.yml:
```
version: '3'

services:
  app:
    deploy:
      replicas: 2
      placement:
        constraints:
         - node.role == worker
      labels:
        - "traefik.backend=app"
        - "traefik.docker.network=${NETWORK}"
        - "traefik.enable=true"
        - "traefik.port=8081"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:${APP}.kluster.kalisio.xyz"
      restart_policy:
        condition: on-failure

  mongodb:
    deploy:
      replicas: 1
      placement:
        constraints:
         - node.role == worker
      restart_policy:
        condition: on-failure
````
And the script to deploy:
```
#!/bin/bash
set -a
. ./.env
set +a

SWARM_NETWORK=`docker network ls | grep swarm-network`
if [ "$SWARM_NETWORK" = "" ]; then
  docker network create -d overlay --attachable swarm-network
fi
docker stack deploy -c aktnmap.yml -c aktnmap.swarm.yml aktnmap
```
