### ISSUE TITLE
An infrastructure should provide a registry

### ISSUE THREAD

**Issue by cnouguier** [kalisio/kaabah#28]
This should allow to build locally a container and then to deploy it

**Comment by cnouguier** [comment]
Could be:
```
version: '3.5'

services:
  registry:
    image: registry:2
    ports:
      - 5000:5000
    networks:
      - kaabah-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  kaabah-network:
    name: ${DOCKER_NETWORK}
    external: true
```
